1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
l = [0,1, 2, 3, 4, 5]
import numpy as np
arr = np.array(l)
print(arr.dtype)

int64


2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])

In [ ]:
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64


3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
import numpy as np

p= [1+2j, 3+4j, 5+6j]
arr=np.array(p)
print(arr.dtype)

complex128


4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
l = [1,2,3,4,5]
import numpy as np
arr = np.array(arr.astype('float32'))
print(arr.dtype)

float32


5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
n = [1.2,3.4,5.6]
import numpy as np
arr = np.array(n)
arr = arr.astype('float32')
print(arr)
print(arr.dtype)

[1.2 3.4 5.6]
float32


6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.

In [ ]:
import numpy as np
arr = np.fromfunction(lambda i, j : i*j, (3,3))
print(arr.shape)
print(arr.size)
print(arr.dtype)


(3, 3)
9
float64


7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
iterable = (i for i in range(5))
np.fromiter(iterable, int)

array([0, 1, 2, 3, 4])

8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [ ]:
import numpy as np
b = np.zeros((3, 4))
print(b.itemsize)
print(b.nbytes)

8
96


9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
import numpy as np
b = np.zeros((3, 4))
print(b.strides)
print(b)


(32, 8)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [ ]:
import numpy as np
b = np.zeros((3, 4))
print(b.shape)
print(b.strides)

(3, 4)
(32, 8)


11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

In [ ]:
import numpy as np
np.zeros((2, 3))


array([[0., 0., 0.],
       [0., 0., 0.]])

12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols

In [ ]:
mat = np.matrix([1,2,3,4])
type(mat)
mat

matrix([[1, 2, 3, 4]])

13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [ ]:
np.arange(1, 10, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [ ]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

In [ ]:
arr1 = np.random.randint(1, 3, (3, 3))

print(arr1)

print(arr1**arr1)

[[1 1 2]
 [2 2 2]
 [1 2 2]]
[[1 1 4]
 [4 4 4]
 [1 4 4]]


16. Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
import numpy as np
l = [1,2,3,4]
arr = np.array(l)
arr

array([1, 2, 3, 4])

17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

In [ ]:
arr = np.random.randint(1, 5, size= (3, 4))
print(arr)
arr_view = arr.view()
print(arr_view)

[[4 1 3 2]
 [1 1 4 2]
 [2 4 4 1]]
[[4 1 3 2]
 [1 1 4 2]
 [2 4 4 1]]


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))
print(arr1)
print(arr2)
print(arr1 + arr2)

[[1 2 2]
 [1 2 2]
 [1 2 2]]
[[2 1 1]
 [2 2 1]
 [1 1 2]]
[[3 3 3]
 [3 4 3]
 [2 3 4]]


19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.

concatenate`.

In [ ]:
import numpy as np
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 4))
print(arr1)
print(arr2)
print(np.concatenate((arr1, arr2), axis=1))

[[2 2 1]
 [1 2 2]
 [2 1 2]]
[[1 1 2 2]
 [1 2 2 2]
 [2 1 2 1]]
[[2 2 1 1 1 2 2]
 [1 2 2 1 2 2 2]
 [2 1 2 2 1 2 1]]


20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
arr = np.random.randint(1,3,(3,3))
print(arr)
print(list(arr))


[[1 2 2]
 [1 1 2]
 [2 2 2]]
[array([1, 2, 2]), array([1, 1, 2]), array([2, 2, 2])]


21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

In [ ]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [ ]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

In [ ]:

np.log10(np.linspace(1, 1000, 5))

array([0.        , 2.39924094, 2.69940408, 2.875206  , 3.        ])

24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(1, 100, (5, 3)))
df

0   1   2
0  96  40  22
1  43  92  57
2  97  30  92
3  54  36  39
4  31  83  15

25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(-100, 10, (5, 3)))
print(df)
df.replace(to_replace=df.lt(0), value=0, inplace=True)
print(df)

    0   1   2
0  -5 -32   1
1 -84  -9 -86
2 -21  -1 -64
3 -66   7  -1
4 -55 -10 -77


ValueError: Series.replace cannot use dict-like to_replace and non-None value

26. Access the 3rd element from the given NumPy array
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr
arr[2]

30

27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1][2]

6

28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])
arr[arr > 5]

array([ 8, 10,  7])

29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:5]

array([3, 4, 5])

30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2,[1,2]]

array([[2, 3],
       [5, 6]])

31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2,[1,2]]

array([[2, 3],
       [5, 6]])

32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[arr_2d>3]

array([4, 5, 6, 7, 8, 9])

33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [ ]:
arr = np.random.randint(1,10,(4,5))
arr[0:2,[1,2]]


array([[5, 1],
       [4, 2]])

34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

In [ ]:
arr = np.random.randint(1,10,(4,5))
arr[0:4,[1,2]]

array([[5, 2],
       [2, 2],
       [6, 3],
       [9, 3]])

35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [ ]:
arr = np.random.randint(1,10,(4,5))
arr[0:4,[1,2]]

array([[8, 9],
       [6, 8],
       [3, 7],
       [5, 7]])

36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
arr = np.random.randint(1,10,(4,5))
print(arr)
v=arr + 5
print(v)

[[3 7 6 7 8]
 [9 2 6 2 4]
 [6 8 5 9 9]
 [4 5 2 3 9]]
[[ 8 12 11 12 13]
 [14  7 11  7  9]
 [11 13 10 14 14]
 [ 9 10  7  8 14]]


37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [ ]:
import numpy as np
arr1 = np.random.randint(1, 3, (1,3))
arr2 = np.random.randint(3, 4, (3,4))
np.multiply(arr1, arr2)



ValueError: operands could not be broadcast together with shapes (1,3) (3,4) 

38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [ ]:
arr1 = np.random.randint(1, 3, (1,4))
arr2 = np.random.randint(3, 4, (4,3))
result = np.add(arr1, arr2)
result

ValueError: operands could not be broadcast together with shapes (1,4) (4,3) 

39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [ ]:
arr1 = np.random.randint(1, 3, (3,1))
arr2 = np.random.randint(3, 4, (1,3))
result = np.add(arr1, arr2)
result

array([[5, 5, 5],
       [5, 5, 5],
       [4, 4, 4]])

40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility

In [ ]:
arr1 = np.random.randint(1, 3, (2,3))
arr2 = np.random.randint(3, 4, (2,2))
result = np.multiply(arr1, arr2)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

41. Calculate column wise mean for the given array:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.mean(axis=0)


array([2.5, 3.5, 4.5])

42. Find maximum value in each row of the given array:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.max(axis=1)

array([3, 6])

43. For the given array, find indices of maximum value in each column.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.max(axis=0)


array([[1, 2, 3],
       [4, 5, 6]])

44. For the given array, apply custom function to calculate moving sum along rows.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.cumsum(arr, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

45. In the given array, check if all elements in each column are even.

In [ ]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
np.all(arr % 2 == 0, axis=0)


array([False, False, False])

46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.

In [ ]:
arr = np.random.randint(1, 5, size= (3, 4))
arr

arr1 = arr.reshape(12, 1)
arr1

array([[3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [4],
       [2],
       [4],
       [4],
       [1],
       [3]])

47. Create a function that takes a matrix as input and returns the flattened array.

In [ ]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
input_matrix.flatten()

array([1, 2, 3, 4, 5, 6])

48. Write a function that concatenates two given arrays along a specified axis.

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
np.concatenate((array1, array2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

49. Create a function that splits an array into multiple sub-arrays along a specified axis.

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.array_split(original_array, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

50. Write a function that inserts and then deletes elements from a given array at specified indices.

In [ ]:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
np.insert(original_array, indices_to_insert, values_to_insert)
np.delete(original_array, indices_to_delete)


array([1, 3, 5])

51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [ ]:
arr1 = np.random.randint(1, 5, size= (3, 4))
arr2 = np.random.randint(1, 10, size= (3, 4))
print(arr1)
print(arr2)
print(arr1 + arr2)

[[4 3 1 2]
 [2 4 3 1]
 [1 4 4 4]]
[[7 3 7 2]
 [8 9 2 1]
 [1 3 3 4]]
[[11  6  8  4]
 [10 13  5  2]
 [ 2  7  7  8]]


52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.


In [ ]:
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
print(arr1)
print(arr2)
print(arr2 - arr1)

[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]
[-9 -7 -5 -3 -1  1  3  5  7  9]


53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [ ]:
arr1 = np.random.randint(1, 5, size= (3, 4))
arr2 = np.random.randint(1, 5, size= (3, 4))
print(arr1)
print(arr2)
print(arr1 * arr2)

[[1 4 2 2]
 [3 3 1 1]
 [1 1 1 2]]
[[1 3 2 4]
 [4 3 1 2]
 [2 2 2 1]]
[[ 1 12  4  8]
 [12  9  1  2]
 [ 2  2  2  2]]


54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.


In [ ]:
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
print(arr1)
print(arr2)
print(arr1 / arr2)

[ 2  4  6  8 10]
[1 2 3 4 5]
[2. 2. 2. 2. 2.]


55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [ ]:
arr1 = np.arange(1, 6)
arr2 = np.arange(5, 0, -1)
print(arr1)
print(arr2)
print(arr1 ** arr2)

[1 2 3 4 5]
[5 4 3 2 1]
[ 1 16 27 16  5]


56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [ ]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
np.char.count(arr, 'hello')

array([1, 0, 1, 0, 1])

57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
np.char.upper(arr)

array(['HELLO', 'WORLD', 'OPENAI', 'GPT'], dtype='<U6')

58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.


In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
np.char.replace(arr, 'apple', 'orange')


array(['orange', 'banana', 'grape', 'pineorange'], dtype='<U10')

59. Write a function that concatenates strings in a NumPy array element-wise.

In [ ]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
np.char.add(arr1, arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
np.char.str_len(arr)

array([5, 6, 5, 9])

61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [1]:
import numpy as np
arr = np.random.randint(1, 1000, size=100)
print(arr)
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))

[531 174 351 323 789 831 982 935 143 334 960 555 456 843 260 565 525 367
 780 416 885 460  81 770  69 964 571 668 115 608 616 119 680  75 604  69
 995 796 526 564 320 118 623 745 990 586 714 999 768 616 731 171 757 688
 651 102 141 553 750 447 757 693 833 507 575 981 459 108  25 547 589 648
 585 556 329 357 316 321 720 812 835  69 292  88 549 662 306 597 709 903
 313 200  26 170 445  13 680  27 496 364]
512.87
555.5
77360.9531
278.13837042019213


62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [2]:
arr = np.random.randint(1, 100, size=50)
print(arr)
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

[45 73 64 18 74 27 24 24  6 48 22 77 95 46 28 84 34 66 12  7 74 26 13 21
 25 88 85  1 96 36 94 43 27 97 52 61 14 96  7 81 18 10 79 36 47 79  7 64
 98 58]
22.5
76.25


63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [3]:
arr = np.random.randint(1, 100, size=50)
arr2 = np.random.randint(1, 100, size=50)
print(arr)
print(arr2)
print(np.corrcoef(arr, arr2))

[43 62 62 35  3 33 49 18 81 41 84 36 66 57  8 76 15 99 13 43 36 58 50 48
 68 41 54 26 79 30 81 30 38 29 26 95 86  2 59 95  1 97 12 75 49 28 60 49
 42 69]
[47 70 38 39 64 15 38 78 67 78 11 40 27 77 60 19 63 70  4  2 31 23 77 95
 32 45 11 69 25 51 33 60 85 19 25  8 36 88 14 60 40  9  4 56 55 62 11 85
 16  9]
[[ 1.         -0.20943383]
 [-0.20943383  1.        ]]


64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [4]:
arr1 = np.random.randint(1, 10, (3, 3))
arr2 = np.random.randint(1, 10, (3, 3))
print(arr1)
print(arr2)
print(np.dot(arr1, arr2))

[[8 4 2]
 [3 7 3]
 [2 8 4]]
[[1 7 7]
 [9 8 1]
 [6 7 6]]
[[ 56 102  72]
 [ 84  98  46]
 [ 98 106  46]]


65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [5]:
arr = np.random.randint(10, 1000, size=50)
print(arr)
print(np.percentile(arr, 10))
print(np.percentile(arr, 50))
print(np.percentile(arr, 90))

[913 338 682 987 368 357 164 858 900 825 435 231 741 909 625 756 978 625
 247 940 284  73 624 243 792 942  46 802 196 772 297 966 839 190 343 663
 791 108 323  27 358 637 581 664 930 739 811 466 373 373]
187.4
625.0
931.0


66. Create a NumPy array of integers and find the index of a specific element.

In [6]:
arr = np.random.randint(1, 10, size=50)
print(arr)
print(np.where(arr == 5))

[6 5 9 4 4 4 4 7 7 1 8 6 1 6 8 9 3 1 2 6 5 9 6 6 2 4 5 4 3 2 4 4 8 4 3 2 8
 9 3 4 7 9 2 3 8 5 1 2 1 8]
(array([ 1, 20, 26, 45]),)


67. Generate a random NumPy array and sort it in ascending order.

In [7]:
arr = np.random.randint(1, 10, size=50)
print(arr)
print(np.sort(arr))

[8 9 8 6 7 1 3 6 9 4 1 2 6 9 4 1 7 9 1 4 2 5 4 8 6 9 8 9 4 7 8 8 5 5 7 9 9
 1 6 8 4 6 2 1 5 8 3 8 3 4]
[1 1 1 1 1 1 2 2 2 3 3 3 4 4 4 4 4 4 4 5 5 5 5 6 6 6 6 6 6 7 7 7 7 8 8 8 8
 8 8 8 8 8 9 9 9 9 9 9 9 9]


68. Filter elements >20  in the given NumPy array.

In [8]:
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr > 20]

array([25, 42, 30])

69. Filter elements which are divisible by 3 from a given NumPy array.

In [9]:
arr = np.array([1, 5, 8, 12, 15])
arr[arr % 3 == 0]

array([12, 15])

70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

In [10]:
arr = np.array([10, 20, 30, 40, 50])
arr[(arr >= 20) & (arr <= 40)]

array([20, 30, 40])

71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

In [14]:
arr = np.array([1, 2, 3])
print(arr.itemsize)


8


72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

In [16]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.

In [18]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.

In [19]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.

In [21]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.dtype.byteorder

'='

76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `ar

In [22]:
arr1 = np.array([1, 2, 3, 4, 5])
copy_arr = arr1.copy()
copy_arr[0] = 10
print(arr1)
print(copy_arr)

[1 2 3 4 5]
[10  2  3  4  5]


77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [23]:
arr = np.random.randint(1, 10, (3, 3))
print(arr)
arr1 = arr[0:2, 0:2]
print(arr1)
arr1[0, 0] = 10
print(arr)

[[9 8 7]
 [1 8 5]
 [1 7 2]]
[[9 8]
 [1 8]]
[[10  8  7]
 [ 1  8  5]
 [ 1  7  2]]


78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [25]:
arr = np.arange(1, 13).reshape(4, 3)
print(arr)
arr1 = arr[0:2, 0:2]
print(arr1)
arr1 = arr1 + 5

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2]
 [4 5]]


79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [26]:
arr = np.arange(1, 9).reshape(2, 4)
arr.reshape(4, 2)
arr[0, 0] = 10
print(arr)

[[10  2  3  4]
 [ 5  6  7  8]]


80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data

In [27]:
arr = np.random.randint(1, 10, (3, 4))
print(arr)
arr1 = arr[arr > 5].copy()
arr1[0, 0] = 10

[[3 1 2 8]
 [4 2 7 4]
 [7 7 5 3]]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them

In [28]:
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))
print(a)
print(b)
print(a + b)
print(a - b)

[[8 3 6]
 [1 8 2]
 [3 9 2]]
[[6 4 1]
 [1 5 6]
 [8 4 5]]
[[14  7  7]
 [ 2 13  8]
 [11 13  7]]
[[ 2 -1  5]
 [ 0  3 -4]
 [-5  5 -3]]


82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication

In [29]:
c = np.random.randint(1, 10, (3, 2))
d = np.random.randint(1, 10, (2, 4))
print(c)
print(d)
print(np.dot(c, d))

[[5 3]
 [7 8]
 [6 6]]
[[6 9 7 2]
 [9 7 2 7]]
[[ 57  66  41  31]
 [114 119  65  70]
 [ 90  96  54  54]]


83. Create a matrix `E` and find its transpose.

In [30]:
e = np.random.randint(1, 10, (3, 3))
print(e)
print(e.transpose())

[[9 3 7]
 [6 2 3]
 [9 4 2]]
[[9 6 9]
 [3 2 4]
 [7 3 2]]


84. Generate a square matrix `F` and compute its determinant.

In [31]:
f = np.random.randint(1, 10, (3, 3))
print(f)
print(np.linalg.det(f))

[[1 8 3]
 [8 3 9]
 [5 3 1]]
298.9999999999999


85. Create a square matrix `G` and find its inverse.

In [32]:
g = np.random.randint(1, 10, (3, 3))
print(g)
print(np.linalg.inv(g))

[[5 1 8]
 [9 8 8]
 [9 5 9]]
[[-0.49230769 -0.47692308  0.86153846]
 [ 0.13846154  0.41538462 -0.49230769]
 [ 0.41538462  0.24615385 -0.47692308]]
